const VERSION = '0.8.1';
const STATES = ['idle', 'walk', 'attack', 'skill', 'hit', 'guard', 'victory', 'retreat'];

const PROFILES = {
  cao: { name:'조조', role:'군주 · 기병', body:'lean', face:'sharp', eyes:'narrow', skin:'#d7a27e', hair:'#17191d', main:'#202832', sub:'#6f2f39', trim:'#d4a94f', head:'commander', beard:'short', weapon:'sword', armor:'command', emblem:'魏', mount:'#302722', scar:'' },
  xiahou: { name:'하후돈', role:'선봉 · 보병', body:'tall', face:'square', eyes:'stern', skin:'#c98f69', hair:'#15181a', main:'#243d55', sub:'#315f83', trim:'#d0a55f', head:'heavy', beard:'short', weapon:'spear', armor:'heavy', emblem:'守', scar:'eyepatch' },
  dian: { name:'전위', role:'수호 · 호위', body:'massive', face:'square', eyes:'wide', skin:'#b66f50', hair:'#1a1311', main:'#432b27', sub:'#914b33', trim:'#d0a35e', head:'band', beard:'wide', weapon:'halberd', armor:'brutal', emblem:'護', scar:'cheek' },
  xun: { name:'순욱', role:'내정 · 책사', body:'slim', face:'long', eyes:'calm', skin:'#e3b48f', hair:'#29251f', main:'#d9d5ca', sub:'#3d6878', trim:'#d1ad63', head:'scholar', beard:'thin', weapon:'scroll', armor:'robe', emblem:'政', scar:'' },
  guo: { name:'곽가', role:'기책 · 책사', body:'slim', face:'sharp', eyes:'tired', skin:'#ddaa86', hair:'#18151d', main:'#322942', sub:'#724492', trim:'#c9a35d', head:'hood', beard:'', weapon:'fan', armor:'robe', emblem:'策', scar:'' },
  xu: { name:'허저', role:'철벽 · 호위', body:'massive', face:'round', eyes:'deep', skin:'#b97851', hair:'#1b1815', main:'#394239', sub:'#66775c', trim:'#c8a460', head:'heavy', beard:'wide', weapon:'shield', armor:'heavy', emblem:'壁', scar:'brow' },
  liu: { name:'유비', role:'군주 · 보병', body:'balanced', face:'long', eyes:'gentle', skin:'#dfac87', hair:'#29211b', main:'#285b45', sub:'#4f8b60', trim:'#d4b15f', head:'soft', beard:'short', weapon:'dual', armor:'command', emblem:'蜀', scar:'' },
  guan: { name:'관우', role:'돌파 · 기병', body:'tall', face:'long', eyes:'stern', skin:'#ad6550', hair:'#171714', main:'#1f5940', sub:'#397c50', trim:'#d5ae55', head:'band', beard:'long', weapon:'guandao', armor:'lamellar', emblem:'義', mount:'#342820', scar:'' },
  zhang: { name:'장비', role:'맹공 · 기병', body:'massive', face:'square', eyes:'wide', skin:'#9f5b43', hair:'#151212', main:'#602b2a', sub:'#a04436', trim:'#d69d4e', head:'band', beard:'wild', weapon:'spear', armor:'brutal', emblem:'雷', mount:'#30251f', scar:'nose' },
  zhao: { name:'조운', role:'구원 · 기병', body:'athletic', face:'sharp', eyes:'focused', skin:'#dfac86', hair:'#27282b', main:'#b8c4c8', sub:'#49738b', trim:'#d8bd78', head:'light', beard:'', weapon:'spear', armor:'lamellar', emblem:'救', mount:'#d8ddd8', scar:'' },
  'soldier-spear': { name:'창병대', role:'일반 · 보병', body:'balanced', face:'round', eyes:'plain', skin:'#bd825f', hair:'#222018', main:'#405941', sub:'#71804f', trim:'#b79a58', head:'soldier', beard:'', weapon:'spear', armor:'lamellar', emblem:'兵', scar:'' },
  'soldier-archer': { name:'궁병대', role:'일반 · 궁병', body:'slim', face:'round', eyes:'plain', skin:'#c48b65', hair:'#292319', main:'#596046', sub:'#8a7145', trim:'#c0a166', head:'band', beard:'', weapon:'bow', armor:'leather', emblem:'弓', scar:'' },
};
const NAME_TO_ID = new Map(Object.entries(PROFILES).map(([id,p]) => [p.name,id]));
let serial = 0;
let queued = false;
let lastUnits = new Map();
const timers = new WeakMap();
const ns = 'http://www.w3.org/2000/svg';

const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid = (prefix,id) => `${prefix}-${id}-${++serial}`;

function metrics(body){ return ({slim:[32,22],lean:[37,25],balanced:[41,28],athletic:[42,25],tall:[45,28],massive:[53,37]})[body] || [41,28]; }
function jaw(p,cx,cy,s=1){
  const d={sharp:`M${cx-24*s},${cy-22*s}Q${cx-27*s},${cy+8*s} ${cx-13*s},${cy+29*s}Q${cx},${cy+43*s} ${cx+13*s},${cy+29*s}Q${cx+27*s},${cy+8*s} ${cx+24*s},${cy-22*s}Z`,square:`M${cx-27*s},${cy-21*s}Q${cx-29*s},${cy+12*s} ${cx-20*s},${cy+33*s}Q${cx},${cy+42*s} ${cx+20*s},${cy+33*s}Q${cx+29*s},${cy+12*s} ${cx+27*s},${cy-21*s}Z`,long:`M${cx-23*s},${cy-24*s}Q${cx-25*s},${cy+13*s} ${cx-12*s},${cy+37*s}Q${cx},${cy+50*s} ${cx+12*s},${cy+37*s}Q${cx+25*s},${cy+13*s} ${cx+23*s},${cy-24*s}Z`,round:`M${cx-28*s},${cy-19*s}Q${cx-31*s},${cy+14*s} ${cx-18*s},${cy+32*s}Q${cx},${cy+46*s} ${cx+18*s},${cy+32*s}Q${cx+31*s},${cy+14*s} ${cx+28*s},${cy-19*s}Z`};
  return d[p.face] || d.round;
}
function eyes(p,cx,cy,s=1){
  const wide=p.eyes==='wide'?12:p.eyes==='gentle'?11:9, pupil=p.eyes==='wide'?2.2:1.7, brow=(p.eyes==='stern'||p.eyes==='narrow')?4:0;
  return `<path class="cv-brow" d="M${cx-24*s},${cy-10*s}Q${cx-16*s},${cy-(14+brow)*s} ${cx-7*s},${cy-9*s}M${cx+7*s},${cy-9*s}Q${cx+16*s},${cy-(14+brow)*s} ${cx+24*s},${cy-10*s}"/><path class="cv-eye-line" d="M${cx-23*s},${cy}Q${cx-16*s},${cy-4*s} ${cx-(23-wide)*s},${cy+s}M${cx+(23-wide)*s},${cy+s}Q${cx+16*s},${cy-4*s} ${cx+23*s},${cy}"/><ellipse class="cv-eye" cx="${cx-17*s}" cy="${cy-s}" rx="${pupil*s}" ry="${(pupil+.4)*s}"/><ellipse class="cv-eye" cx="${cx+17*s}" cy="${cy-s}" rx="${pupil*s}" ry="${(pupil+.4)*s}"/>`;
}
function head(p,cx,cy,s=1){
  const {main:m,sub:u,trim:t}=p;
  if(p.head==='commander')return `<g class="cv-head"><path d="M${cx-27*s},${cy+11*s}Q${cx-22*s},${cy-10*s} ${cx},${cy-18*s}Q${cx+22*s},${cy-10*s} ${cx+27*s},${cy+11*s}L${cx+20*s},${cy+20*s}H${cx-20*s}Z" fill="${m}" stroke="${t}"/><path d="M${cx},${cy-18*s}V${cy-35*s}M${cx-7*s},${cy-30*s}Q${cx},${cy-40*s} ${cx+10*s},${cy-31*s}" stroke="${u}" stroke-width="${5*s}" fill="none"/></g>`;
  if(p.head==='heavy'||p.head==='light'||p.head==='soldier'){const h=p.head==='heavy'?30:26;return `<g class="cv-head"><path d="M${cx-h*s},${cy+16*s}Q${cx-(h-3)*s},${cy-13*s} ${cx},${cy-22*s}Q${cx+(h-3)*s},${cy-13*s} ${cx+h*s},${cy+16*s}L${cx+20*s},${cy+23*s}H${cx-20*s}Z" fill="${m}" stroke="${t}"/><path d="M${cx-h*s},${cy+11*s}H${cx+h*s}" stroke="${t}" stroke-width="${3*s}"/>${p.head!=='soldier'?`<path d="M${cx},${cy-22*s}V${cy-38*s}Q${cx+13*s},${cy-47*s} ${cx+19*s},${cy-33*s}" stroke="${u}" stroke-width="${5*s}" fill="none"/>`:''}</g>`;}
  if(p.head==='scholar')return `<g class="cv-head"><path d="M${cx-22*s},${cy+16*s}Q${cx-18*s},${cy-18*s} ${cx+12*s},${cy-17*s}Q${cx+22*s},${cy} ${cx+22*s},${cy+16*s}Z" fill="${m}" stroke="${t}"/><path d="M${cx+10*s},${cy-14*s}L${cx+31*s},${cy-27*s}" stroke="${t}" stroke-width="${3*s}"/></g>`;
  if(p.head==='hood')return `<path class="cv-head" d="M${cx-32*s},${cy+24*s}Q${cx-34*s},${cy-16*s} ${cx},${cy-27*s}Q${cx+34*s},${cy-16*s} ${cx+32*s},${cy+24*s}L${cx+21*s},${cy+10*s}Q${cx+15*s},${cy-7*s} ${cx},${cy-11*s}Q${cx-15*s},${cy-7*s} ${cx-21*s},${cy+10*s}Z" fill="${m}" stroke="${t}"/>`;
  if(p.head==='soft')return `<path class="cv-head" d="M${cx-24*s},${cy+13*s}Q${cx-19*s},${cy-12*s} ${cx},${cy-15*s}Q${cx+19*s},${cy-12*s} ${cx+24*s},${cy+13*s}L${cx+16*s},${cy+19*s}H${cx-16*s}Z" fill="${m}" stroke="${t}"/>`;
  return `<g class="cv-head"><path d="M${cx-29*s},${cy+12*s}Q${cx},${cy-4*s} ${cx+29*s},${cy+12*s}L${cx+25*s},${cy+19*s}Q${cx},${cy+8*s} ${cx-25*s},${cy+19*s}Z" fill="${u}" stroke="${t}"/><path d="M${cx+25*s},${cy+14*s}Q${cx+43*s},${cy+23*s} ${cx+35*s},${cy+35*s}" stroke="${u}" stroke-width="${8*s}" fill="none"/></g>`;
}
function beard(p,cx,cy,s=1){
  const h=p.hair;
  if(p.beard==='short'||p.beard==='thin')return `<path class="cv-beard" d="M${cx-13*s},${cy}Q${cx},${cy+14*s} ${cx+13*s},${cy}Q${cx+10*s},${cy+28*s} ${cx},${cy+31*s}Q${cx-10*s},${cy+28*s} ${cx-13*s},${cy}Z" fill="${h}" opacity="${p.beard==='thin'?.78:1}"/>`;
  if(p.beard==='wide'||p.beard==='wild')return `<path class="cv-beard" d="M${cx-29*s},${cy-3*s}Q${cx-17*s},${cy+15*s} ${cx-9*s},${cy+11*s}Q${cx},${cy+19*s} ${cx+9*s},${cy+11*s}Q${cx+17*s},${cy+15*s} ${cx+29*s},${cy-3*s}Q${cx+24*s},${cy+31*s} ${cx+12*s},${cy+39*s}Q${cx},${cy+31*s} ${cx-12*s},${cy+39*s}Q${cx-24*s},${cy+31*s} ${cx-29*s},${cy-3*s}Z" fill="${h}"/>`;
  if(p.beard==='long')return `<path class="cv-beard" d="M${cx-19*s},${cy-1*s}Q${cx},${cy+20*s} ${cx+19*s},${cy-1*s}Q${cx+18*s},${cy+47*s} ${cx+7*s},${cy+77*s}L${cx},${cy+89*s}L${cx-8*s},${cy+72*s}Q${cx-18*s},${cy+43*s} ${cx-19*s},${cy-1*s}Z" fill="${h}"/>`;
  return '';
}
function scar(p,cx,cy,s=1){if(p.scar==='eyepatch')return `<path d="M${cx+4*s},${cy-10*s}L${cx+29*s},${cy-24*s}" stroke="#161313" stroke-width="${4*s}"/><rect x="${cx+9*s}" y="${cy-7*s}" width="${15*s}" height="${11*s}" rx="${3*s}" fill="#161313" stroke="${p.trim}"/>`; if(p.scar)return `<path d="M${cx-22*s},${cy+6*s}l${8*s},${11*s}" stroke="#843b31" stroke-width="${2*s}"/>`;return '';}
function armor(p,cx,top,s=1){const [chest,waist]=metrics(p.body), c=chest*s,w=waist*s;if(p.armor==='robe')return `<path d="M${cx-c},${top+6*s}Q${cx-c-8*s},${top+36*s} ${cx-w},${top+79*s}H${cx+w}Q${cx+c+8*s},${top+36*s} ${cx+c},${top+6*s}L${cx+16*s},${top-8*s}H${cx-16*s}Z" fill="${p.main}" stroke="${p.trim}"/><path d="M${cx-14*s},${top-6*s}L${cx},${top+15*s}L${cx+14*s},${top-6*s}" stroke="${p.sub}" stroke-width="${4*s}" fill="none"/>`;return `<g><path d="M${cx-c},${top+6*s}Q${cx-c-14*s},${top+17*s} ${cx-w},${top+76*s}H${cx+w}Q${cx+c+14*s},${top+17*s} ${cx+c},${top+6*s}L${cx+15*s},${top-9*s}H${cx-15*s}Z" fill="${p.main}" stroke="${p.trim}"/><path d="M${cx-c-3*s},${top+9*s}Q${cx-c-18*s},${top+21*s} ${cx-c-8*s},${top+39*s}L${cx-c+9*s},${top+33*s}Z M${cx+c+3*s},${top+9*s}Q${cx+c+18*s},${top+21*s} ${cx+c+8*s},${top+39*s}L${cx+c-9*s},${top+33*s}Z" fill="${p.sub}" stroke="${p.trim}"/><path d="M${cx-25*s},${top+17*s}H${cx+25*s}M${cx-27*s},${top+32*s}H${cx+27*s}M${cx-23*s},${top+47*s}H${cx+23*s}" stroke="${p.trim}" stroke-width="${3*s}" opacity=".72"/></g>`;}
function weapon(p,cx,cy,s=1){const a=p.trim,u=p.sub; if(p.weapon==='shield')return `<path class="cv-weapon" d="M${cx+5*s},${cy-28*s}Q${cx+33*s},${cy-27*s} ${cx+30*s},${cy+8*s}Q${cx+21*s},${cy+24*s} ${cx+8*s},${cy+30*s}Q${cx-5*s},${cy+19*s} ${cx-9*s},${cy-9*s}Q${cx-7*s},${cy-27*s} ${cx+5*s},${cy-28*s}Z" fill="${p.main}" stroke="${a}" stroke-width="${3*s}"/>`; if(p.weapon==='fan'||p.weapon==='scroll')return `<path class="cv-weapon" d="M${cx},${cy}Q${cx+14*s},${cy-42*s} ${cx+40*s},${cy-24*s}Q${cx+31*s},${cy+3*s} ${cx},${cy}Z" fill="#eadfc7" stroke="${a}" stroke-width="${2*s}"/>`; if(p.weapon==='bow')return `<g class="cv-weapon"><path d="M${cx+25*s},${cy-49*s}Q${cx-2*s},${cy-20*s} ${cx+25*s},${cy+19*s}M${cx+25*s},${cy-49*s}V${cy+19*s}" fill="none" stroke="${a}" stroke-width="${4*s}"/><path d="M${cx+11*s},${cy-15*s}H${cx+48*s}" stroke="${u}" stroke-width="${3*s}"/></g>`; const blade=p.weapon==='guandao'?`Q${cx+55*s},${cy-68*s} ${cx+50*s},${cy-47*s}Q${cx+39*s},${cy-43*s} ${cx+34*s},${cy-54*s}Z`:`l${11*s},${11*s}-${14*s},${s}z`; return `<g class="cv-weapon"><path d="M${cx-4*s},${cy+8*s}L${cx+39*s},${cy-67*s}" stroke="${a}" stroke-width="${p.weapon==='sword'?5*s:4*s}"/><path d="M${cx+39*s},${cy-67*s}${blade}" fill="${u}" stroke="${a}"/></g>`;}
function horse(p,cx,cy){return `<g class="cv-horse"><ellipse cx="${cx}" cy="${cy}" rx="31" ry="18" fill="${p.mount}" stroke="#161616" stroke-width="2"/><path d="M${cx+22},${cy-12}Q${cx+38},${cy-28} ${cx+46},${cy-17}L${cx+42},${cy+3}Q${cx+31},${cy+4} ${cx+24},${cy-5}Z" fill="${p.mount}" stroke="#161616" stroke-width="2"/><path class="cv-tail" d="M${cx-28},${cy-3}Q${cx-49},${cy-16} ${cx-51},${cy+2}Q${cx-40},${cy+10} ${cx-27},${cy+5}" fill="none" stroke="#181718" stroke-width="6"/><path class="cv-leg back" d="M${cx-17},${cy+12}L${cx-22},${cy+34}M${cx+16},${cy+12}L${cx+23},${cy+34}" stroke="#171716" stroke-width="7"/></g>`;}

function portrait(id){const p=PROFILES[id], bg=uid('cvbg',id);return `<defs><linearGradient id="${bg}" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#111918"/><stop offset=".58" stop-color="${p.main}"/><stop offset="1" stop-color="#080b0b"/></linearGradient></defs><rect width="180" height="220" rx="12" fill="url(#${bg})"/><circle cx="143" cy="43" r="54" fill="${p.trim}" opacity=".12"/><text x="145" y="65" text-anchor="middle" font-size="58" font-family="serif" font-weight="900" fill="${p.trim}" opacity=".17">${p.emblem}</text><g class="cv-portrait-body">${armor(p,90,137,1)}<path d="${jaw(p,90,72,1)}" fill="${p.skin}" stroke="#5d372f"/><path d="M64,69Q65,34 90,31Q117,35 116,69Q104,51 90,52Q75,51 64,69Z" fill="${p.hair}"/>${head(p,90,42,1)}${eyes(p,90,77,1)}<path class="cv-nose" d="M90,81Q87,96 92,101Q96,101 98,98"/><path class="cv-mouth" d="M78,111Q90,115 102,111"/>${scar(p,90,77,1)}${beard(p,90,108,1)}</g><g class="cv-plaque"><rect x="10" y="168" width="77" height="42" rx="7" fill="rgba(6,9,8,.78)" stroke="${p.trim}"/><text x="20" y="184" font-size="8" fill="${p.trim}">${esc(p.role)}</text><text x="20" y="203" font-size="18" font-weight="900" fill="#fff2dc">${esc(p.name)}</text></g>`;}
function unit(id){const p=PROFILES[id],[chest]=metrics(p.body),cx=p.mount?57:60,base=p.mount?63:70,s=.54,top=base+8,c=chest*s;return `<defs><radialGradient id="${uid('aura',id)}"><stop stop-color="${p.trim}" stop-opacity=".55"/><stop offset="1" stop-color="${p.trim}" stop-opacity="0"/></radialGradient></defs><ellipse class="cv-shadow" cx="60" cy="127" rx="39" ry="8" fill="rgba(0,0,0,.36)"/><circle class="cv-aura" cx="60" cy="69" r="48" fill="${p.trim}" opacity="0"/>${p.mount?horse(p,58,96):`<g class="cv-legs"><path class="cv-leg back" d="M${cx-10},${top+36}L${cx-15},126M${cx+10},${top+36}L${cx+15},126" stroke="${p.main}" stroke-width="7"/></g>`}<g class="cv-unit-body"><path class="cv-cape" d="M${cx-c-8},${top+3}Q${cx},${top-16} ${cx+c+8},${top+3}L${cx+25},${top+48}H${cx-25}Z" fill="${p.main}" opacity=".83"/><path d="M${cx-c},${top}Q${cx-c-8},${top+16} ${cx-16},${top+48}H${cx+16}Q${cx+c+8},${top+16} ${cx+c},${top}L${cx+8},${top-10}H${cx-8}Z" fill="${p.sub}" stroke="${p.trim}" stroke-width="2"/><g class="cv-arm back"><path d="M${cx-c+2},${top+8}Q${cx-c-10},${top+28} ${cx-c},${top+44}" stroke="${p.main}" stroke-width="6" fill="none"/></g><g class="cv-arm front"><path d="M${cx+c-2},${top+8}Q${cx+c+11},${top+27} ${cx+c+3},${top+44}" stroke="${p.sub}" stroke-width="6" fill="none"/></g><path d="${jaw(p,cx,base-17,s)}" fill="${p.skin}" stroke="#5b342c"/><path d="M${cx-24*s},${base-36*s}Q${cx},${base-54*s} ${cx+24*s},${base-36*s}Q${cx+14*s},${base-48*s} ${cx},${base-47*s}Q${cx-14*s},${base-48*s} ${cx-24*s},${base-36*s}Z" fill="${p.hair}"/>${head(p,cx,base-45*s,s*.84)}${eyes(p,cx,base-21*s,s*.7)}${scar(p,cx,base-21*s,s*.72)}${beard(p,cx,base-8*s,s*.62)}${weapon(p,cx+c-1,top+44,.72)}</g>`;}

function idFor(svg){const label=(svg.getAttribute('aria-label')||'').trim();return NAME_TO_ID.get(label)||Object.keys(PROFILES).find(id=>label.includes(PROFILES[id].name))||'';}
function isUnit(svg){return !!svg.closest('.battle-unit') || /\b(unit|micro|tiny)\b/.test(svg.getAttribute('class')||'');}
function renderSvg(svg,id,kind=isUnit(svg)?'unit':'portrait'){const p=PROFILES[id];if(!p)return;svg.dataset.commercialArtV2='1';svg.dataset.heroId=id;svg.dataset.silhouette=`${p.body}:${p.face}:${p.head}:${p.weapon}`;svg.dataset.state='idle';svg.classList.add('commercial-art-v2',kind==='unit'?'commercial-unit-v2':'commercial-portrait-v2');svg.setAttribute('viewBox',kind==='unit'?'0 0 120 140':'0 0 180 220');svg.innerHTML=kind==='unit'?unit(id):portrait(id);const host=svg.closest('.battle-unit');if(host){host.dataset.commercialHeroId=id;host.style.setProperty('--commercial-accent',p.trim);}}
function setState(svg,state,duration=0){if(!svg||!STATES.includes(state))return;clearTimeout(timers.get(svg));svg.dataset.state=state;if(duration)timers.set(svg,setTimeout(()=>{if(svg.isConnected)svg.dataset.state='idle';},duration));}
function motionLayer(){let l=document.querySelector('#commercial-motion-v2');if(!l){l=document.createElement('div');l.id='commercial-motion-v2';l.className='commercial-motion-v2';document.body.append(l);}return l;}
function impact(rect,tone='slash'){const e=document.createElement('div');e.className=`commercial-impact-v2 ${tone}`;e.style.left=`${rect.left+rect.width/2}px`;e.style.top=`${rect.top+rect.height/2}px`;e.innerHTML='<i></i><i></i><i></i><b></b>';motionLayer().append(e);setTimeout(()=>e.remove(),780);}
function overlay(id,rect,state){const w=document.createElement('div');w.className=`commercial-overlay-v2 ${state}`;Object.assign(w.style,{left:`${rect.left}px`,top:`${rect.top}px`,width:`${Math.max(55,rect.width)}px`,height:`${Math.max(62,rect.height)}px`});const svg=document.createElementNS(ns,'svg');svg.setAttribute('class','hero-portrait unit');svg.setAttribute('aria-label',PROFILES[id].name);renderSvg(svg,id,'unit');svg.dataset.state=state;w.append(svg);motionLayer().append(w);return w;}
function animateIntent(event){const t=event.target instanceof Element?event.target:null, selected=document.querySelector('.battle-unit.player.selected[data-commercial-hero-id]');if(!t||!selected)return;const id=selected.dataset.commercialHeroId,from=selected.getBoundingClientRect(),enemy=t.closest('.battle-unit.enemy'),cell=t.closest('.battle-cell.reachable'),mode=document.querySelector('.command-grid button.active[data-action]')?.dataset.action||'command-move';let to=null,state='';if(enemy&&(mode==='command-attack'||mode==='command-skill')){to=enemy.getBoundingClientRect();state=mode==='command-skill'?'skill':'attack';}else if(cell&&mode==='command-move'){to=cell.getBoundingClientRect();state='walk';}if(!to||!state)return;const o=overlay(id,from,state),dx=to.left-from.left,dy=to.top-from.top;selected.classList.add('commercial-ghost');const frames=state==='walk'?[{transform:'translate(0,0)',offset:0},{transform:`translate(${dx*.2}px,${dy*.2-6}px)`,offset:.2},{transform:`translate(${dx*.42}px,${dy*.42+1}px)`,offset:.42},{transform:`translate(${dx*.64}px,${dy*.64-7}px)`,offset:.64},{transform:`translate(${dx*.83}px,${dy*.83}px)`,offset:.83},{transform:`translate(${dx}px,${dy}px)`,offset:1}]:[{transform:'translate(0,0) scale(1)'},{transform:`translate(${dx*.16}px,${dy*.16}px) scale(.95)`},{transform:`translate(${dx*.48}px,${dy*.48}px) scale(1.16)`},{transform:'translate(0,0) scale(1)'}];const d=state==='walk'?680:state==='skill'?850:620;o.animate(frames,{duration:d,easing:'cubic-bezier(.18,.75,.24,1)',fill:'forwards'});if(state!=='walk')setTimeout(()=>impact(to,state==='skill'?'skill':(PROFILES[id].weapon==='bow'?'projectile':'slash')),d*.55);setState(selected.querySelector('svg.commercial-unit-v2'),state,d);setTimeout(()=>{o.remove();selected.classList.remove('commercial-ghost');},d+80);}
function snapshots(){const m=new Map();document.querySelectorAll('.battle-unit[data-unit]').forEach(u=>{const svg=u.querySelector('svg.commercial-unit-v2');if(!svg)return;const r=u.getBoundingClientRect(),hp=Number.parseInt((u.querySelector('.unit-label span')?.textContent||'0').split('/')[0],10)||0;m.set(u.dataset.unit,{u,svg,r,hp,id:svg.dataset.heroId});});return m;}
function compare(next){for(const [key,n] of next){const p=lastUnits.get(key);if(p&&n.hp<p.hp){setState(n.svg,'hit',450);impact(n.r,'hit');}if(p&&(Math.abs(p.r.left-n.r.left)>4||Math.abs(p.r.top-n.r.top)>4)){const dx=p.r.left-n.r.left,dy=p.r.top-n.r.top;setState(n.svg,'walk',650);n.u.animate([{transform:`translate(${dx}px,${dy}px)`},{transform:`translate(${dx*.6}px,${dy*.6-5}px)`},{transform:`translate(${dx*.25}px,${dy*.25+1}px)`},{transform:'translate(0,0)'}],{duration:650,easing:'ease-out'});}}for(const [key,p] of lastUnits){if(next.has(key))continue;const o=overlay(p.id,p.r,'retreat');o.animate([{opacity:1,transform:'scale(1)'},{opacity:0,transform:'translate(22px,15px) scale(.55)'}],{duration:700,fill:'forwards'});setTimeout(()=>o.remove(),740);}}
function addInspectors(){document.querySelectorAll('.roster-card[data-hero]:not([data-cv2])').forEach(card=>{const id=card.dataset.hero;if(!PROFILES[id])return;card.dataset.cv2='1';(card.querySelector('.roster-copy')||card).insertAdjacentHTML('beforeend',`<button class="cv2-detail" data-cv2-detail="${id}" type="button">캐릭터 아트 · 동작 보기</button>`);});}
function openDetail(id){if(document.querySelector('.cv2-modal'))return;const p=PROFILES[id],m=document.createElement('div');m.className='cv2-modal';m.innerHTML=`<div class="cv2-backdrop" data-cv2-close></div><section><header><div><small>CHARACTER QUALITY REVIEW</small><b>${esc(p.name)}</b><span>${esc(p.role)}</span></div><button data-cv2-close>×</button></header><div class="cv2-scroll"><div class="cv2-profile"><div class="cv2-portrait"><svg class="hero-portrait story" aria-label="${esc(p.name)}"></svg></div><article><small>SILHOUETTE</small><h2>${esc(p.name)}</h2><p>${esc(p.role)}</p><dl><div><dt>체형</dt><dd>${p.body}</dd></div><div><dt>얼굴</dt><dd>${p.face} · ${p.eyes}</dd></div><div><dt>장비</dt><dd>${p.head} · ${p.weapon}</dd></div></dl><blockquote>체형·얼굴형·눈매·갑옷·무기·자세를 장수별로 분리한 벡터 알파입니다.</blockquote></article></div><div class="cv2-states">${STATES.map(s=>`<article data-cv2-state="${s}"><div><svg class="hero-portrait unit" aria-label="${esc(p.name)}"></svg></div><b>${s}</b></article>`).join('')}</div></div><footer><span>commercial-alpha 품질 검수 전용</span><button data-cv2-close>돌아가기</button></footer></section>`;document.body.append(m);m.querySelectorAll('svg.hero-portrait').forEach(svg=>renderSvg(svg,id,isUnit(svg)?'unit':'portrait'));m.querySelectorAll('[data-cv2-state]').forEach(a=>a.querySelector('svg').dataset.state=a.dataset.cv2State);requestAnimationFrame(()=>m.classList.add('show'));}
function closeDetail(){const m=document.querySelector('.cv2-modal');if(!m)return;m.classList.remove('show');setTimeout(()=>m.remove(),220);}
function enhance(){queued=false;document.documentElement.classList.add('commercial-character-art-v2');document.querySelectorAll('svg.hero-portrait:not([data-commercial-art-v2])').forEach(svg=>{const id=idFor(svg);if(id)renderSvg(svg,id);});addInspectors();const next=snapshots();compare(next);lastUnits=next;window.__commercialCharacterArtV2={ready:true,version:VERSION,heroes:Object.keys(PROFILES),heroCount:Object.keys(PROFILES).length,states:[...STATES],renderer:'vector-svg'};}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(enhance);}
document.addEventListener('pointerdown',animateIntent,true);document.addEventListener('click',e=>{const t=e.target instanceof Element?e.target:null;if(!t)return;const d=t.closest('[data-cv2-detail]');if(d){e.preventDefault();e.stopPropagation();openDetail(d.dataset.cv2Detail);}if(t.closest('[data-cv2-close]')){e.preventDefault();closeDetail();}},true);new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['class','style']});schedule();