const PIXEL_ART_VERSION = '20260818-9';
const STATES = ['idle', 'move', 'attack', 'skill'];
const HEROES = {
  cao:{name:'조조',role:'군주 · 기병',p:'#24252d',s:'#5b377f',t:'#d4a94f',skin:'#ddb08d',hair:'#151518',eye:'#241c22',head:'crown',beard:'short',weapon:'sword',type:'cavalry',accent:'#8d59c7',mount:'#4b3427'},
  xiahou:{name:'하후돈',role:'선봉 · 보병',p:'#1f3549',s:'#285f8a',t:'#d2aa63',skin:'#cf9874',hair:'#141719',eye:'#211d1b',head:'helm',beard:'short',weapon:'spear',type:'infantry',accent:'#4a8bc2',patch:true},
  dian:{name:'전위',role:'수호 · 호위',p:'#3f2a25',s:'#8f4d2f',t:'#d0a55d',skin:'#b97552',hair:'#1a1412',eye:'#231815',head:'band',beard:'wide',weapon:'halberd',type:'guardian',accent:'#d77b3f'},
  xun:{name:'순욱',role:'내정 · 책사',p:'#e3ddd0',s:'#365f74',t:'#d0a95f',skin:'#e7b995',hair:'#27231f',eye:'#2d2622',head:'cap',beard:'short',weapon:'scroll',type:'strategist',accent:'#5ba3b0'},
  guo:{name:'곽가',role:'기책 · 책사',p:'#30253f',s:'#6d3b88',t:'#c6a05a',skin:'#dfaf8a',hair:'#16141a',eye:'#281e27',head:'hood',beard:'none',weapon:'fan',type:'strategist',accent:'#a65bce'},
  xu:{name:'허저',role:'철벽 · 호위',p:'#394036',s:'#667557',t:'#c7a25c',skin:'#bc7c55',hair:'#1a1815',eye:'#241b17',head:'helm',beard:'wide',weapon:'shield',type:'guardian',accent:'#94a569'},
  liu:{name:'유비',role:'군주 · 보병',p:'#285b42',s:'#4f8c5d',t:'#d3b15e',skin:'#dfad87',hair:'#282019',eye:'#2b241f',head:'crown',beard:'short',weapon:'dual',type:'infantry',accent:'#65b777'},
  guan:{name:'관우',role:'돌파 · 기병',p:'#1f5a3b',s:'#397849',t:'#d5ae55',skin:'#b86f55',hair:'#151514',eye:'#211815',head:'band',beard:'long',weapon:'guandao',type:'cavalry',accent:'#52a768',mount:'#3d2b22'},
  zhang:{name:'장비',role:'맹공 · 기병',p:'#5e2725',s:'#9e3d30',t:'#d39e4f',skin:'#a85f46',hair:'#151212',eye:'#211612',head:'band',beard:'wide',weapon:'spear',type:'cavalry',accent:'#df5b45',mount:'#3a2921'},
  zhao:{name:'조운',role:'구원 · 기병',p:'#b9c7ca',s:'#446e86',t:'#d7bd77',skin:'#dfad86',hair:'#252629',eye:'#2b2825',head:'helm',beard:'none',weapon:'spear',type:'cavalry',accent:'#83bed9',mount:'#e2e5df'},
  'soldier-spear':{name:'창병대',role:'일반 · 보병',p:'#3f5a3e',s:'#71834f',t:'#b89a58',skin:'#bd825d',hair:'#222018',eye:'#241d18',head:'helm',beard:'short',weapon:'spear',type:'infantry',accent:'#8ba762'},
  'soldier-archer':{name:'궁병대',role:'일반 · 궁병',p:'#596046',s:'#8a7145',t:'#c0a166',skin:'#c48b65',hair:'#292319',eye:'#2b211b',head:'band',beard:'none',weapon:'bow',type:'archer',accent:'#b89b5e'},
};
const ORDER = Object.keys(HEROES);
const NAME_TO_ID = Object.fromEntries(ORDER.map(id => [HEROES[id].name,id]));
let scheduled=false, modalOpen=false, lastIntent=0;

function rgb(hex){const v=hex.replace('#','');return [0,2,4].map(i=>parseInt(v.slice(i,i+2),16));}
function color(hex,a=1){const [r,g,b]=Array.isArray(hex)?hex:rgb(hex);return `rgba(${r},${g},${b},${a})`;}
function mix(a,b,t){const A=rgb(a),B=rgb(b);return A.map((v,i)=>Math.round(v*(1-t)+B[i]*t));}
function ctxCanvas(w,h,klass,label){const c=document.createElement('canvas');c.width=w;c.height=h;c.className=klass;c.setAttribute('role','img');c.setAttribute('aria-label',label);c.style.imageRendering='pixelated';return c;}
function R(c,x,y,w,h,fill,stroke=''){c.fillStyle=color(fill);c.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h));if(stroke){c.strokeStyle=color(stroke);c.lineWidth=1;c.strokeRect(Math.round(x)+.5,Math.round(y)+.5,Math.round(w)-1,Math.round(h)-1);}}
function P(c,pts,fill,stroke=''){c.beginPath();pts.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();c.fillStyle=color(fill);c.fill();if(stroke){c.strokeStyle=color(stroke);c.lineWidth=1;c.stroke();}}
function L(c,pts,stroke,w=1){c.beginPath();pts.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.strokeStyle=color(stroke);c.lineWidth=w;c.lineCap='square';c.stroke();}
function E(c,x,y,w,h,fill,stroke=''){c.beginPath();c.ellipse(x+w/2,y+h/2,w/2,h/2,0,0,Math.PI*2);if(fill){c.fillStyle=color(fill);c.fill();}if(stroke){c.strokeStyle=color(stroke);c.lineWidth=1;c.stroke();}}
function arc(c,x,y,r,a1,a2,stroke,w=1){c.beginPath();c.arc(x,y,r,a1,a2);c.strokeStyle=color(stroke);c.lineWidth=w;c.stroke();}

function headgear(c,h,cx,cy,s=1){const p=h.p,q=h.s,t=h.t;if(h.head==='crown'){P(c,[[cx-9*s,cy],[cx-6*s,cy-9*s],[cx-2*s,cy-4*s],[cx,cy-12*s],[cx+3*s,cy-4*s],[cx+8*s,cy-9*s],[cx+9*s,cy]],p,t);R(c,cx-10*s,cy,20*s,3*s,q,t);E(c,cx-2*s,cy-11*s,4*s,4*s,t);}else if(h.head==='helm'){P(c,[[cx-10*s,cy+4*s],[cx-8*s,cy-5*s],[cx,cy-10*s],[cx+8*s,cy-5*s],[cx+10*s,cy+4*s]],p,t);R(c,cx-10*s,cy+2*s,20*s,3*s,q,t);L(c,[[cx,cy-10*s],[cx,cy-16*s]],t,Math.max(1,s));P(c,[[cx,cy-16*s],[cx+5*s,cy-13*s],[cx,cy-12*s]],q);}else if(h.head==='band'){R(c,cx-10*s,cy,20*s,3*s,q,t);P(c,[[cx+9*s,cy+2*s],[cx+17*s,cy+8*s],[cx+12*s,cy+10*s]],q);}else if(h.head==='hood'){P(c,[[cx-11*s,cy+8*s],[cx-10*s,cy-4*s],[cx,cy-11*s],[cx+10*s,cy-4*s],[cx+11*s,cy+8*s],[cx+6*s,cy+5*s],[cx+4*s,cy-2*s],[cx,cy-5*s],[cx-4*s,cy-2*s],[cx-6*s,cy+5*s]],p,t);}else{P(c,[[cx-8*s,cy+3*s],[cx-6*s,cy-10*s],[cx+5*s,cy-10*s],[cx+8*s,cy+3*s]],p,t);R(c,cx-9*s,cy+2*s,18*s,3*s,q,t);L(c,[[cx+5*s,cy-9*s],[cx+11*s,cy-15*s]],t,Math.max(1,s));}}

function weapon(c,h,x,y,size,pose='idle',f=1){const t=h.t,q=h.s,d=mix(h.p,'#000000',.3),w=Math.max(1,Math.round(size*.08));if(['spear','guandao','halberd'].includes(h.weapon)){let x2=x+f*size*.28,y2=y-size*.9;if(pose==='attack'){x2=x+f*size*.9;y2=y-size*.35;}L(c,[[x,y],[x2,y2]],t,w);if(h.weapon==='spear')P(c,[[x2,y2],[x2-f*size*.14,y2+size*.05],[x2-f*size*.06,y2+size*.16]],q,t);else if(h.weapon==='guandao')P(c,[[x2,y2],[x2-f*size*.28,y2-size*.05],[x2-f*size*.18,y2+size*.2],[x2-f*size*.04,y2+size*.13]],q,t);else{P(c,[[x2,y2],[x2-f*size*.22,y2-size*.08],[x2-f*size*.15,y2+size*.14],[x2-f*size*.02,y2+size*.09]],q,t);P(c,[[x2-f*size*.02,y2+size*.09],[x2+f*size*.12,y2+size*.16],[x2+f*size*.05,y2+size*.02]],d,t);}}else if(['sword','dual'].includes(h.weapon)){const dx=f*size*.55,dy=size*(pose==='attack'?-0.55:-1.1);L(c,[[x,y],[x+dx,y+dy]],t,w);P(c,[[x+dx,y+dy],[x+dx-f*size*.12,y+dy+size*.04],[x+dx-f*size*.04,y+dy+size*.14]],q,t);if(h.weapon==='dual')L(c,[[x-f*size*.12,y],[x-f*size*.45,y-size*.5]],t,w);}else if(h.weapon==='shield'){P(c,[[x-f*size*.15,y-size*.55],[x+f*size*.35,y-size*.48],[x+f*size*.28,y+size*.05],[x+f*size*.08,y+size*.25],[x-f*size*.18,y]],d,t);L(c,[[x+f*size*.08,y-size*.43],[x+f*size*.08,y+size*.12]],t,w);}else if(h.weapon==='fan'){P(c,[[x,y],[x+f*size*.42,y-size*.36],[x+f*size*.52,y-size*.02]],mix(h.s,'#ffffff',.5),t);for(let k=0;k<3;k++)L(c,[[x,y],[x+f*size*(.18+.1*k),y-size*(.12+.08*k)]],d,1);}else if(h.weapon==='scroll'){R(c,x-f*size*.1,y-size*.35,f*size*.55,size*.29,mix('#efe2c2',h.p,.1),t);L(c,[[x,y-size*.28],[x+f*size*.35,y-size*.28]],d,1);}else if(h.weapon==='bow'){L(c,[[x,y-size*.6],[x+f*size*.15,y+size*.15]],t,w);L(c,[[x,y-size*.6],[x-f*size*.18,y-size*.25],[x+f*size*.15,y+size*.15]],q,w);if(pose==='attack')L(c,[[x-f*size*.1,y-size*.24],[x+f*size*.7,y-size*.28]],t,w);}}

function drawPortrait(id,klass){const h=HEROES[id],canvas=ctxCanvas(64,80,klass,`${h.name} 픽셀 초상`),c=canvas.getContext('2d');c.imageSmoothingEnabled=false;R(c,0,0,64,80,mix(h.p,'#050706',.58));P(c,[[35,0],[64,0],[64,36],[28,46]],mix(h.s,'#0a0e0b',.55));for(let y=3;y<80;y+=5)for(let x=(y*3)%7;x<64;x+=7)if((x*13+y*7)%5===0)R(c,x,y,1,1,mix(h.t,'#ffffff',.15));R(c,2,2,60,76,mix(h.t,'#000000',.22));R(c,4,4,56,72,mix(h.p,'#ffffff',.12));P(c,[[42,5],[60,4],[57,48],[39,45]],mix(h.s,'#000000',.35));for(let k=0;k<4;k++)R(c,46+k*2,10,1,25,mix(h.t,'#000000',.15));P(c,[[6,79],[10,54],[22,43],[42,43],[56,57],[62,79]],h.p,'#050605');P(c,[[12,78],[16,54],[31,47],[48,55],[54,78]],h.s,h.t);E(c,7,48,19,13,mix(h.p,'#000000',.18),h.t);E(c,39,48,19,13,mix(h.p,'#000000',.18),h.t);[12,17,44,49].forEach(x=>R(c,x,52,3,3,h.t));R(c,27,39,10,11,h.skin);E(c,20,16,24,31,h.skin,mix(h.hair,'#000000',.15));R(c,19,29,2,7,h.skin);R(c,43,29,2,7,h.skin);P(c,[[20,29],[20,21],[24,15],[31,12],[39,15],[44,21],[44,29],[40,23],[35,21],[29,22],[24,24]],h.hair);E(c,28,8,9,9,h.hair);L(c,[[24,29],[29,27]],h.eye,2);L(c,[[35,27],[40,29]],h.eye,2);R(c,26,30,2,1,'#f5e6d2');R(c,36,30,2,1,'#f5e6d2');R(c,27,30,1,1,h.eye);R(c,37,30,1,1,h.eye);if(h.patch){R(c,34,26,6,7,'#151313',h.t);L(c,[[33,26],[42,20]],'#151313',2);}L(c,[[32,31],[31,36],[34,37]],mix(h.skin,'#7c4735',.55));L(c,[[28,40],[36,40]],'#703d34');if(h.beard==='short')P(c,[[26,39],[32,44],[38,39],[36,49],[32,52],[27,48]],h.hair);else if(h.beard==='long'){P(c,[[24,38],[32,45],[40,38],[38,57],[33,68],[29,58],[26,49]],h.hair);L(c,[[31,46],[32,62]],mix(h.hair,'#ffffff',.18));}else if(h.beard==='wide')P(c,[[20,37],[26,44],[32,42],[38,44],[44,37],[41,51],[36,56],[32,52],[28,56],[22,50]],h.hair);headgear(c,h,32,17,1);L(c,[[31,50],[31,78]],h.t);L(c,[[21,57],[31,62],[43,56]],mix(h.t,'#ffffff',.1));weapon(c,h,48,70,22,'idle',1);for(let i=0;i<6;i++)R(c,10+i*8,70-(i%2)*3,1,1,h.t);return canvas;}

function horse(c,h,x,y,pose,f=1){const q=h.mount||'#4a3428',d=mix(q,'#000000',.35);E(c,x-7,y-4,15,8,q,d);P(c,[[x+6*f,y-2],[x+11*f,y-6],[x+13*f,y-4],[x+10*f,y+1]],q,d);P(c,[[x+11*f,y-6],[x+10*f,y-9],[x+12*f,y-7]],d);L(c,[[x+7*f,y-5],[x+10*f,y-1]],h.t);const legs=pose==='move'?[[-5,-1,-8,7],[1,-1,5,7],[5,1,9,6],[-1,1,-4,6]]:[[-5,1,-6,8],[1,1,0,8],[5,1,7,8],[-1,1,-2,8]];legs.forEach(([a,b,d1,e])=>L(c,[[x+a,y+b],[x+d1,y+e]],d,2));L(c,[[x-7*f,y-1],[x-13*f,y-5],[x-14*f,y]],d,2);R(c,x-3,y-5,7,5,h.s,h.t);}
function drawSprite(id,state,klass){const h=HEROES[id],canvas=ctxCanvas(32,32,klass,`${h.name} ${state} 픽셀 유닛`),c=canvas.getContext('2d');c.imageSmoothingEnabled=false;if(state==='skill'){[[13,mix(h.accent,'#ffffff',.15)],[10,h.accent],[7,mix(h.accent,'#ffffff',.4)]].forEach(([r,col])=>E(c,16-r,16-r,r*2,r*2,'',col));for(let k=0;k<8;k++)R(c,4+(k*7)%24,3+(k*11)%21,1,2,h.t);}else if(state==='attack'){arc(c,18,16,14,3.6,5.8,h.accent,3);arc(c,18,16,11,3.6,5.8,mix(h.accent,'#ffffff',.45),1);}E(c,5,25,22,5,[0,0,0,90]);const mounted=h.type==='cavalry';let by=mounted?14:21;if(mounted)horse(c,h,15,23,state,1);if(!mounted){if(state==='move'){L(c,[[14,23],[10,29]],mix(h.p,'#000000',.25),3);L(c,[[19,23],[24,28]],mix(h.p,'#000000',.25),3);}else{L(c,[[14,23],[13,29]],mix(h.p,'#000000',.25),3);L(c,[[19,23],[20,29]],mix(h.p,'#000000',.25),3);}}P(c,[[11,by+9],[12,by-2],[16,by-6],[21,by-2],[23,by+9]],h.p,'#070807');P(c,[[13,by+8],[14,by],[17,by-3],[21,by+1],[22,by+8]],h.s,h.t);E(c,13,by-12,9,10,h.skin,h.hair);P(c,[[13,by-7],[13,by-13],[17,by-17],[22,by-12],[22,by-7],[19,by-11],[16,by-10]],h.hair);headgear(c,h,17,by-12,.45);R(c,15,by-8,1,1,h.eye);R(c,19,by-8,1,1,h.eye);if(h.patch)R(c,18,by-10,4,3,'#151313');if(h.beard==='long')P(c,[[14,by-5],[17,by-1],[21,by-5],[20,by+4],[17,by+7],[15,by+2]],h.hair);else if(h.beard==='wide')P(c,[[12,by-5],[17,by-1],[22,by-5],[21,by+2],[18,by+5],[15,by+3],[13,by+2]],h.hair);else if(h.beard==='short')P(c,[[14,by-4],[17,by],[21,by-4],[20,by+2],[17,by+4],[15,by+2]],h.hair);weapon(c,h,21,by+7,13,state,1);if(state==='move'){R(c,4,28,2,1,mix(h.t,'#ffffff',.2));R(c,8,30,2,1,mix(h.t,'#ffffff',.2));}if(state==='skill'){for(let k=0;k<5;k++)R(c,5+k*5,4+(k%2)*3,2,2,mix(h.accent,'#ffffff',.35));}return canvas;}

function idFromSvg(svg){return NAME_TO_ID[svg.getAttribute('aria-label')?.trim()||'']||'';}
function stateForSvg(svg){return /\bunit\b|\bmicro\b/.test(svg.getAttribute('class')||'')?'idle':'portrait';}
function applyMeta(el,id,state){el.dataset.pixelHero=id;el.dataset.pixelState=state;el.style.setProperty('--pixel-tone',HEROES[id].accent);}
function replacePortraits(root=document){root.querySelectorAll('svg.hero-portrait:not([data-pixel-scan])').forEach(svg=>{svg.dataset.pixelScan='1';const id=idFromSvg(svg);if(!id)return;const state=stateForSvg(svg),klass=`${svg.getAttribute('class')||'hero-portrait'} pixel-character-v2 ${state==='portrait'?'pixel-portrait-v2':'pixel-sprite-v2'}`,art=state==='portrait'?drawPortrait(id,klass):drawSprite(id,'idle',klass);const style=svg.getAttribute('style');if(style)art.setAttribute('style',style);applyMeta(art,id,state);const unit=svg.closest('.battle-unit');if(unit){unit.dataset.pixelHero=id;unit.style.setProperty('--pixel-tone',HEROES[id].accent);}svg.replaceWith(art);});}
function enhanceRoster(root=document){root.querySelectorAll('.roster-card[data-hero]:not([data-pixel-roster])').forEach(card=>{const id=card.dataset.hero;if(!HEROES[id])return;card.dataset.pixelRoster='1';card.style.setProperty('--pixel-tone',HEROES[id].accent);card.querySelector('.roster-art')?.insertAdjacentHTML('beforeend',`<span class="pixel-art-badge" data-pixel-detail="${id}"><i>◆</i> 픽셀 무장 상세</span>`);});}
function enhanceStory(root=document){root.querySelectorAll('.story-character:not([data-pixel-story])').forEach(stage=>{if(!stage.querySelector('.pixel-portrait-v2'))return;stage.dataset.pixelStory='1';stage.insertAdjacentHTML('beforeend','<span class="pixel-story-credit">PIXEL OFFICER ART · 12 HEROES</span>');});}
function enhanceUnits(root=document){root.querySelectorAll('.battle-unit[data-pixel-hero]:not([data-pixel-unit])').forEach(unit=>{unit.dataset.pixelUnit='1';unit.insertAdjacentHTML('beforeend','<span class="pixel-unit-ring"></span>');});}
function openSheet(id){if(modalOpen||!HEROES[id])return;modalOpen=true;const h=HEROES[id],modal=document.createElement('div');modal.className='pixel-sheet-modal';modal.innerHTML=`<div class="pixel-sheet-backdrop" data-pixel-sheet-close></div><section style="--pixel-tone:${h.accent}"><header><div><small>PIXEL OFFICER FILE</small><b>${h.name}</b><span>${h.role}</span></div><button type="button" data-pixel-sheet-close>×</button></header><div class="pixel-sheet-scroll"><div class="pixel-detail-layout"><div class="pixel-sheet-portrait"></div><aside><small>ALL CHARACTER PIXEL SET</small><h2>${h.name}</h2><p>${h.role}</p><div class="pixel-state-grid"></div><blockquote>픽셀 초상과 전투용 대기·이동·공격·기술 상태를 하나의 캐릭터 규격으로 통일했습니다.</blockquote></aside></div></div><footer><span>게임에 등장하는 12종 캐릭터 모두 픽셀 자산으로 적용됩니다.</span><button type="button" data-pixel-sheet-close>게임으로 돌아가기</button></footer></section>`;const portrait=drawPortrait(id,'pixel-sheet-portrait-art');modal.querySelector('.pixel-sheet-portrait').replaceWith(portrait);const grid=modal.querySelector('.pixel-state-grid');STATES.forEach(state=>{const article=document.createElement('article'),art=drawSprite(id,state,'pixel-state-art');article.append(art);article.insertAdjacentHTML('beforeend',`<b>${({idle:'대기',move:'이동',attack:'공격',skill:'기술'})[state]}</b>`);grid.append(article);});document.body.append(modal);requestAnimationFrame(()=>modal.classList.add('show'));}
function closeSheet(){const modal=document.querySelector('.pixel-sheet-modal');if(!modal)return;modal.classList.remove('show');setTimeout(()=>{modal.remove();modalOpen=false;},220);}
function rectOf(el){const r=el?.getBoundingClientRect();return r&&r.width&&r.height?r:null;}
function overlay(id,state,from,to=null,duration=520){if(!HEROES[id]||!from)return;const el=drawSprite(id,state,`pixel-action-sprite-v2 ${state}`);applyMeta(el,id,state);Object.assign(el.style,{left:`${from.left}px`,top:`${from.top}px`,width:`${Math.max(52,from.width)}px`,height:`${Math.max(52,from.height)}px`});document.body.append(el);requestAnimationFrame(()=>{el.classList.add('play');if(to)el.style.transform=`translate(${to.left-from.left}px,${to.top-from.top}px) scale(${state==='move'?1:1.16})`;});setTimeout(()=>el.classList.add('fade'),Math.max(180,duration-150));setTimeout(()=>el.remove(),duration+80);}
function burst(r,kind='attack'){if(!r)return;const e=document.createElement('div');e.className=`pixel-hit-fx-v2 ${kind}`;e.style.left=`${r.left+r.width/2}px`;e.style.top=`${r.top+r.height/2}px`;e.innerHTML='<i></i><b></b><span></span><em></em>';document.body.append(e);setTimeout(()=>e.remove(),760);}
function activeCommand(){return document.querySelector('.command-grid button.active[data-action]')?.dataset.action||'';}
function animateIntent(event){if(performance.now()-lastIntent<80)return;const target=event.target instanceof Element?event.target:null,selected=document.querySelector('.battle-unit.player.selected[data-pixel-hero]');if(!target||!selected)return;const id=selected.dataset.pixelHero,from=rectOf(selected),command=activeCommand(),enemy=target.closest('.battle-unit.enemy');if(enemy&&['command-attack','command-skill'].includes(command)){lastIntent=performance.now();const to=rectOf(enemy),state=command==='command-skill'?'skill':'attack';overlay(id,state,from,to,state==='skill'?720:540);burst(to,state);return;}const cell=target.closest('.battle-cell.reachable');if(cell&&command==='command-move'){lastIntent=performance.now();overlay(id,'move',from,rectOf(cell),500);}}
function enhance(){scheduled=false;document.documentElement.classList.add('pixel-character-art-v2','pixel-character-art-ready');replacePortraits();enhanceRoster();enhanceStory();enhanceUnits();}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(enhance);}
document.addEventListener('click',event=>{const target=event.target instanceof Element?event.target:null;if(!target)return;const detail=target.closest('[data-pixel-detail]');if(detail){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();openSheet(detail.dataset.pixelDetail);return;}if(target.closest('[data-pixel-sheet-close]')){event.preventDefault();closeSheet();}},true);
document.addEventListener('pointerdown',animateIntent,true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modalOpen)closeSheet();});new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});window.__pixelArtV2={ready:true,heroCount:ORDER.length,heroes:[...ORDER],version:PIXEL_ART_VERSION};document.documentElement.dataset.pixelHeroCount=String(ORDER.length);schedule();